<?php

Dict::Add('RU RU', 'Russian', 'Русский', array(
	// Dictionary entries go here
	'Menu:Templates' => 'Шаблоны',
	'Menu:Templates+' => 'Templates for object creation forms',
	'Templates:UserData' => 'Дополнительные данные',
	'Templates:Need' => 'Need',

	'Templates:PreviewTab:Title' => 'Предварительный просмотр',
	'Templates:PreviewTab:FormFields' => 'Пример формы',
	'Templates:PreviewTab:HiddenFields' => 'Скрытое поле',

	'Class:Template' => 'Шаблон',
	'Class:Template+' => 'Шаблон для создания объектов на портале',
	'Class:Template/Attribute:name' => 'Название',
	'Class:Template/Attribute:name+' => 'Внутренее название',
	'Class:Template/Attribute:label' => 'Заголовок',
	'Class:Template/Attribute:label+' => 'Заголовок используется на форме',
	'Class:Template/Attribute:description' => 'Описание',
	'Class:Template/Attribute:description+' => 'Описание используется на форме',
	'Class:Template/Attribute:field_list' => 'Поля',
	'Class:Template/Attribute:field_list+' => '',

	'Class:TemplateField' => 'Поле',
	'Class:TemplateField+' => '',
	'Class:TemplateField/Attribute:template_id' => 'Шаблон',
	'Class:TemplateField/Attribute:template_id+' => '',
	'Class:TemplateField/Attribute:template_id_finalclass_recall' => 'Тип',
	'Class:TemplateField/Attribute:template_id_finalclass_recall+' => '',
	'Class:TemplateField/Attribute:code' => 'Код поля',
	'Class:TemplateField/Attribute:code+' => 'Код поля или любое другое значение',
	'Class:TemplateField/Attribute:label' => 'Заголовок',
	'Class:TemplateField/Attribute:label+' => 'Отображается на форме',
	'Class:TemplateField/Attribute:order' => 'Сортировка',
	'Class:TemplateField/Attribute:order+' => 'Порядок отображения на форме',
	'Class:TemplateField/Attribute:mandatory' => 'Обязательное',
	'Class:TemplateField/Attribute:mandatory+' => '',
	'Class:TemplateField/Attribute:mandatory/Value:yes' => 'Да',
	'Class:TemplateField/Attribute:mandatory/Value:yes+' => '',
	'Class:TemplateField/Attribute:mandatory/Value:no' => 'Нет',
	'Class:TemplateField/Attribute:mandatory/Value:no+' => '',
	'Class:TemplateField/Attribute:input_type' => 'Формат данных',
	'Class:TemplateField/Attribute:input_type+' => '',
	'Class:TemplateField/Attribute:input_type/Value:text' => 'Строка',
	'Class:TemplateField/Attribute:input_type/Value:text+' => '',
	'Class:TemplateField/Attribute:input_type/Value:text_area' => 'Текстовый блок',
	'Class:TemplateField/Attribute:input_type/Value:text_area+' => '',
	'Class:TemplateField/Attribute:input_type/Value:drop_down_list' => 'Выподающий список',
	'Class:TemplateField/Attribute:input_type/Value:drop_down_list+' => '',
	'Class:TemplateField/Attribute:input_type/Value:radio_buttons' => 'Список',
	'Class:TemplateField/Attribute:input_type/Value:radio_buttons+' => '',
	'Class:TemplateField/Attribute:input_type/Value:date' => 'Дата',
	'Class:TemplateField/Attribute:input_type/Value:date+' => '',
	'Class:TemplateField/Attribute:input_type/Value:date_and_time' => 'Дата и время',
	'Class:TemplateField/Attribute:input_type/Value:date_and_time+' => '',
	'Class:TemplateField/Attribute:input_type/Value:duration' => 'Duration',
	'Class:TemplateField/Attribute:input_type/Value:duration+' => '',
	'Class:TemplateField/Attribute:input_type/Value:read_only' => 'Только для чтения',
	'Class:TemplateField/Attribute:input_type/Value:read_only+' => '',
	'Class:TemplateField/Attribute:input_type/Value:hidden' => 'Скрытое',
	'Class:TemplateField/Attribute:input_type/Value:hidden+' => '',
	'Class:TemplateField/Attribute:values' => 'Значение (OQL или CSV)',
	'Class:TemplateField/Attribute:values+' => '"SELECT myClass AS c WHERE c.name LIKE \'foo\'" or "val1,val2,..."',
	'Class:TemplateField/Attribute:initial_value' => 'Значение по умолчанию',
	'Class:TemplateField/Attribute:initial_value+' => '',
	'Class:TemplateField/Attribute:format' => 'Формат',
	'Class:TemplateField/Attribute:format+' => 'Регулярное выражение',
));
?>
