<?php

Dict::Add('RU RU', 'Russian', 'Русский', array(
	'Class:AutoAppointment' => 'Триггер автоматического назначения исполнителя',
	'Class:AutoAppointment+' => '',

	'Class:EventNotificationAutoAppointment' => 'Отчет об автоматическом назначении исполнителя',
	'Class:EventNotificationAutoAppointment+' => '',
	'Class:EventNotificationAutoAppointment/Attribute:agent_id' => 'Исполнитель',
	'Class:EventNotificationAutoAppointment/Attribute:agent_id+' => '',
	'Class:EventNotificationAutoAppointment/Attribute:servicesubcategory_id' => 'Услуга',
	'Class:EventNotificationAutoAppointment/Attribute:servicesubcategory_id+' => '',

	'Class:AutoAppointmentRule' => 'Правило автоматического назначения исполнителя',
	'Class:AutoAppointmentRule+' => '',
	'Class:AutoAppointmentRule/Attribute:name' => 'Название',
	'Class:AutoAppointmentRule/Attribute:name+' => '',
	'Class:AutoAppointmentRule/Attribute:org_id' => 'Организация',
	'Class:AutoAppointmentRule/Attribute:org_id+' => '',
	'Class:AutoAppointmentRule/Attribute:team_id' => 'Группа исполнителей',
	'Class:AutoAppointmentRule/Attribute:team_id+' => '',
	'Class:AutoAppointmentRule/Attribute:service_id' => 'Группа услуг',
	'Class:AutoAppointmentRule/Attribute:service_id+' => '',
	'Class:AutoAppointmentRule/Attribute:subservice_id' => 'Услуга',
	'Class:AutoAppointmentRule/Attribute:subservice_id+' => '',
	'Class:AutoAppointmentRule/Attribute:filter' => 'Фильтр',
	'Class:AutoAppointmentRule/Attribute:filter+' => '',

	'Menu:AutoAppointmentRule' => 'Правила автоматического назначения исполнителя',
	'Menu:AutoAppointmentRule+' => 'Все правила автоматического назначения исполнителя',

	'Class:Vacation' => 'Отсутствие в офисе',
	'Class:Vacation+' => '',
	'Class:Vacation/Attribute:name' => 'Причина отсутствия',
	'Class:Vacation/Attribute:name+' => '',
	'Class:Vacation/Attribute:date' => 'Дата',
	'Class:Vacation/Attribute:date+' => '',
	'Class:Vacation/Attribute:person_id' => 'Сотрудник',
	'Class:Vacation/Attribute:person_id+' => '',

	'Class:WorkSchedule' => 'Рабочий график',
	'Class:WorkSchedule+' => '',
	'Class:WorkSchedule/Attribute:person_id' => 'Сотрудник',
	'Class:WorkSchedule/Attribute:person_id+' => '',
	'Class:WorkSchedule/Attribute:date_from' => 'Дата c',
	'Class:WorkSchedule/Attribute:date_from+' => '',
	'Class:WorkSchedule/Attribute:from_h' => 'С (часы)',
	'Class:WorkSchedule/Attribute:from_h+' => '',
	'Class:WorkSchedule/Attribute:from_m' => 'С (минуты)',
	'Class:WorkSchedule/Attribute:from_m+' => '',
	'Class:WorkSchedule/Attribute:date_to' => 'Дата до',
	'Class:WorkSchedule/Attribute:date_to+' => '',
	'Class:WorkSchedule/Attribute:to_h' => 'До (часы)',
	'Class:WorkSchedule/Attribute:to_h+' => '',
	'Class:WorkSchedule/Attribute:to_m' => 'До (минуты)',
	'Class:WorkSchedule/Attribute:to_m+' => '',

    'Person:work_schedule' => 'Упращенный рабочий график',
	'Class:Person/Attribute:schedule' => 'Рабочий график',
	'Class:Person/Attribute:schedule+' => 'Данный рабочий график игнорируется в случае заполнения данных на вкладке Рабочий график',
	'Class:Person/Attribute:schedule/Value:01_disable' => '01. Без графика',
	'Class:Person/Attribute:schedule/Value:02_24_7' => '02. Круглосуточный график',
	'Class:Person/Attribute:schedule/Value:03_5_2' => '03. Стандартный (5 рабочих, 2 выходных)',
	'Class:Person/Attribute:schedule/Value:04_12_12_48' => '04. День Ночь Отсыпной Выходной',
	'Class:Person/Attribute:schedule/Value:05_24_48' => '05. Сутки через двое',
	'Class:Person/Attribute:schedule/Value:06_24_72' => '06. Сутки через трое',
    'Class:Person/Attribute:schedule/Value:07_schedule' => '07. По графику',
	'Class:Person/Attribute:start' => 'Дата начала графика',
	'Class:Person/Attribute:start+' => '',
	'Class:Person/Attribute:is_allow_hollydays' => 'Учитывать отсутствие в офисе',
	'Class:Person/Attribute:is_allow_hollydays+' => '',
	'Class:Person/Attribute:is_allow_hollydays/Value:yes' => 'Да',
	'Class:Person/Attribute:is_allow_hollydays/Value:no' => 'Нет',
	'Class:Person/Attribute:vacation_list' => 'Отсутствие в офисе',
	'Class:Person/Attribute:vacation_list+' => 'Список всех дат отсутствия в офисе, в том числе отгулы и выходные дни',
	'Class:Person/Attribute:works_chedule_list' => 'Рабочий график',
	'Class:Person/Attribute:works_chedule_list+' => 'График работы специалиста',

));
?>