<?php
Dict::Add('RU RU', 'Russian', 'Русский', array(
	'Approval:Tab:Title' => 'Статус согласования',
	'Approval:Tab:Start' => 'Начало',
	'Approval:Tab:End' => 'Конец',
	'Approval:Tab:StepEnd-Limit' => 'Время ожидания (неявный результат)',
	'Approval:Tab:StepEnd-Theoretical' => 'Теоретический срок (продолжительность ограничена %1$s мин)',
	'Approval:Tab:StepSumary-Ongoing' => 'Ожидание ответа',
	'Approval:Tab:StepSumary-OK' => 'Согласовано',
	'Approval:Tab:StepSumary-KO' => 'Отклонено',
	'Approval:Tab:StepSumary-OK-Timeout' => 'Согласовано (по таймауту)',
	'Approval:Tab:StepSumary-KO-Timeout' => 'Отклонено (по таймауту)',
	'Approval:Tab:StepSumary-Idle' => 'Не запущено',
	'Approval:Tab:StepSumary-Skipped' => 'Пропущено',
	'Approval:Tab:End-Abort' => 'Процесс согласования был %1$s при %2$s',

	'Approval:Tab:StepEnd-Condition-FirstReject' => 'Этот шаг заканчивается при первом отказе или если 100% согласовано',
	'Approval:Tab:StepEnd-Condition-FirstApprove' => 'Этот шаг заканчивается при первом одобрении или если 100% отклонено',
	'Approval:Tab:StepEnd-Condition-FirstReply' => 'Этот шаг заканчивается при первом ответе',
	'Approval:Tab:Error' => 'Произошла ошибка во время процесса согласования: %1$s',

	'Approval:Comment-Label' => 'Ваш комментарий',
	'Approval:Comment-Tooltip' => 'Обязательный для отказа, необязательный для согласования',
	'Approval:Comment-Mandatory' => 'Необходимо дать комментарий об отказе',
	'Approval:Comment-Reused' => 'Ответна шаге %1$s предоставлен с комментарием "%2$s"',
	'Approval:Action-Approve' => 'Согласовать',
	'Approval:Action-Reject' => 'Отклонить',
	'Approval:Action-ApproveOrReject' => 'Согласовать или Отклонить',
	'Approval:Action-Abort' => 'Пропуск процесс согласования',

	'Approval:Form:Title' => 'Согласование',
	'Approval:Form:Ref' => 'Процесс согласования для %1$s',

	'Approval:Form:ApproverDeleted' => 'Извините, запись, соответствующая вашей личности, была удалена.',
	'Approval:Form:ObjectDeleted' => 'К сожалению, объект одобрения был удален.',

	'Approval:Form:AnswerGivenBy' => 'Извините, ответ уже сохранен \'%1$s\'', 
	'Approval:Form:AlreadyApproved' => 'Процесс уже завершен с результатом: Согласовано.',
	'Approval:Form:AlreadyRejected' => 'Процесс уже завершен с результатом: Отклонено.',

	'Approval:Form:StepApproved' => 'Данная фаза завершена с результатом: Согласовано. Процесс согласования продолжается ...',
	'Approval:Form:StepRejected' => 'Данная фаза завершена с результатом: Отклонено. Процесс согласования продолжается ...',

	'Approval:Abort:Explain' => 'Вы запросили <strong>пропуск</strong> процесса согласования. Это остановит процесс, и ни один из утвердителей не сможет дать ответ.',

	'Approval:Form:AnswerRecorded-Continue' => 'Ваш ответ записан. Процесс согласования продолжается.',
	'Approval:Form:AnswerRecorded-Approved' => 'Ваш ответ был записан: процесс согласования теперь завершен с результатом СОГЛАСОВАНО.',
	'Approval:Form:AnswerRecorded-Rejected' => 'Ваш ответ был записан: процесс согласования теперь завершен с результатом ОТКЛОНЕНО.',

	'Approval:Approved-On-behalf-of' => 'Утверждено %1$s от имени %2$s',
	'Approval:Rejected-On-behalf-of' => 'Отклонено %1$s от имени %2$s',
	'Approval:Approved-By' => 'Утверждено %1$s',
	'Approval:Rejected-By' => 'Отклонено %1$s',

	'Approval:Ongoing-Title' => 'Текущие согласования',
	'Approval:Ongoing-Title+' => 'Процедуры согласования для объектов класса %1$s',
	'Approval:Ongoing-FilterMyApprovals' => 'Показывать элементы, для которых требуется мое согласование',
	'Approval:Ongoing-NothingCurrently' => 'Нет постоянного согласования.',

	'Approval:Remind-Btn' => 'Отправить напоминание...',
	'Approval:Remind-DlgTitle' => 'Отправить напоминание',
	'Approval:Remind-DlgBody' => 'Следующие контакты будут уведомлены повторно:',
	'Approval:ReminderDone' => 'Напоминание для %1$d отправлено повторно.',

	'Approval:Portal:Title' => 'Элементы, ожидающие вашего согласования',
	'Approval:Portal:Title+' => 'Выберите элементы для согласования и используйте кнопоки, расположенных в нижней части страницы.',
	'Approval:Portal:NoItem' => 'В настоящее время нет ожидающих согласований',
	'Approval:Portal:Btn:Approve' => 'Согласовать',
	'Approval:Portal:Btn:Reject' => 'Отклонить',
	'Approval:Portal:CommentTitle' => 'Комментарий (обязательно в случае отклонения)',
	'Approval:Portal:CommentPlaceholder' => '',
	'Approval:Portal:Success' => 'Ваши ответ сохранен',
	'Approval:Portal:Dlg:Approve' => 'Пожалуйста, подтвердите, что вы хотите одобрить данный <em><span class="approval-count">?</span></em> элемент(ы)',
	'Approval:Portal:Dlg:ApproveOne' => 'Пожалуйста, подтвердите, что вы хотите одобрить данный элемент',
	'Approval:Portal:Dlg:Btn:Approve' => 'Согласовать!',
	'Approval:Portal:Dlg:Reject' => 'Пожалуйста, подтвердите, что вы хотите отклонить этот <em><span class="approval-count">?</span></em> элемент(ы)',
	'Approval:Portal:Dlg:RejectOne' => 'Пожалуйста, подтвердите, что вы хотите отклонить этот элемент',
	'Approval:Portal:Dlg:Btn:Reject' => 'Отклонить!',

	'Class:TriggerOnApprovalRequest' => 'Триггер (при запросе официального согласования)',
	'Class:TriggerOnApprovalRequest+' => 'Запуск процесса согласования',
	'Class:ActionEmailApprovalRequest' => 'Процесс согласования по почте',
	'Class:ActionEmailApprovalRequest/Attribute:subject_reminder' => 'Тема (напоминание)',
	'Class:ActionEmailApprovalRequest/Attribute:subject_reminder+' => 'Тема письма в случае отправки напоминания',
));
